export const SUBJECTS = [
  {
    slug: 'dataviz',
    name: '数据可视化',
    icon: 'dataviz',
    href: '../dataviz/dataviz.html',
    homeHref: 'subjects/dataviz/dataviz.html',
    dir: 'subjects/dataviz',
    config: 'subjects/dataviz/dataviz-config.js',
    questions: 'subjects/dataviz/dataviz-questions.js',
    html: 'subjects/dataviz/dataviz.html',
    questionCount: 300,
    setCount: 3,
    description: '期末复习 300 题，覆盖可视化概述、感知认知、设计美学、数据通道、Tableau。',
    tags: ['单选', '多选', '填空', '简答'],
  },
  {
    slug: 'electronics',
    name: '电子技术基础',
    icon: 'electronics',
    href: '../electronics/electronics.html',
    homeHref: 'subjects/electronics/electronics.html',
    dir: 'subjects/electronics',
    config: 'subjects/electronics/electronics-config.js',
    questions: 'subjects/electronics/electronics-questions.js',
    html: 'subjects/electronics/electronics.html',
    questionCount: 110,
    setCount: 3,
    description: '24-25 学年 A/B 卷与 23-24 A 卷，含填空、判断、计算题，附电路图详细解析。',
    tags: ['判断', '填空', '计算', '电路图'],
  },
  {
    slug: 'machine-learning',
    name: '机器学习',
    icon: 'machineLearning',
    href: '../machine-learning/machine-learning.html',
    homeHref: 'subjects/machine-learning/machine-learning.html',
    dir: 'subjects/machine-learning',
    config: 'subjects/machine-learning/machine-learning-config.js',
    questions: 'subjects/machine-learning/machine-learning-questions.js',
    html: 'subjects/machine-learning/machine-learning.html',
    questionCount: 160,
    setCount: 4,
    description: '期末复习 160 题，覆盖机器学习概述、模型评估、回归、逻辑回归、SVM、神经网络与集成学习。',
    tags: ['单选', '多选', '简答', '计算'],
  },
];

export function getSubjectLinks(activeSlug) {
  return SUBJECTS.map((subject) => ({
    name: subject.name,
    icon: subject.icon,
    href: subject.href,
    active: subject.slug === activeSlug,
  }));
}
